###
# your planet news site title

title = ScummVM Planet



###
# add some web feeds to your news site

[strangerke]
  title = Strangerke&#039;s Sandbox
  link  = https://strangerke.blogspot.com/
  feed  = https://strangerke.blogspot.com/feeds/posts/default

[sev]
  title = Sev&#039;s ScummVM notes
  link  = https://sev-notes.blogspot.com/
  feed  = https://sev-notes.blogspot.com/feeds/posts/default

[giucam]
  title = Lost Souls&#039; Alliance Headquarters
  link  = https://lostsoulsalliance.wordpress.com/
  feed  = https://lostsoulsalliance.wordpress.com/feed/

[t7gre]
  title = Groovie, baby
  link  = https://t7gre.blogspot.com/
  feed  = https://t7gre.blogspot.com/feeds/posts/default

[dreammaster]
  title = Dreammaster&#039;s disassembly blog
  link  = https://dm-notes.blogspot.com/
  feed  = https://dm-notes.blogspot.com/feeds/posts/default

[sanguinehearts]
  title = sanguinehearts
  link  = https://sanguinehearts.blogspot.com/
  feed  = https://sanguinehearts.blogspot.com/feeds/posts/default

[scummvm]
  title = ScummVM news
  link  = http://www.scummvm.org/
  feed  = https://www.scummvm.org/feeds/atom/

[criezy]
  title = Criezy&#039;s Blog
  link  = https://criezy.blogspot.com/
  feed  = https://criezy.blogspot.com/feeds/posts/default

[gsoc2025-aun]
  title = GSoC 2025 - Aun
  link  = https://blogs.scummvm.org/prime
  feed  = https://blogs.scummvm.org/prime/feed/

[gsoc2025-ellen]
  title = GSoC 2025 - Ellen
  link  = https://blogs.scummvm.org/ellen/
  feed  = https://blogs.scummvm.org/ellen/feed/

[gsoc2025-alikhan]
  title = GSoC 2025 - Alikhan
  link  = https://blogs.scummvm.org/alikhan
  feed  = https://blogs.scummvm.org/alikhan/feed/

[gsoc2025-malhar]
  title = GSoC 2025 - Malhar
  link  = https://blogs.scummvm.org/superlemon
  feed  = https://blogs.scummvm.org/superlemon/feed/

[gsoc2025-shivang]
  title = GSoC 2025 - Shivang
  link  = https://blogs.scummvm.org/shivangnagta
  feed  = https://blogs.scummvm.org/shivangnagta/feed/

[gsoc2026-mohit]
  title = GSoC 2026 - Mohit
  link  = https://blogs.scummvm.org/mohit
  feed  = https://blogs.scummvm.org/mohit/feed/

[gsoc2026-ramyak]
  title = GSoC 2026 - Ramyak
  link  = https://blogs.scummvm.org/ramyak
  feed  = https://blogs.scummvm.org/ramyak/feed/

[gsoc2026-priyanshu]
  title = GSoC 2026 - Priyanshu
  link  = https://blogs.scummvm.org/priyanshu
  feed  = https://blogs.scummvm.org/priyanshu/feed/

[gsoc2026-andy]
  title = GSoC 2026 - Andy
  link  = https://blogs.scummvm.org/andy
  feeed = https://blogs.scummvm.org/andy/feed/
