[project]
name = "buildbot-director"
version = "0.2.0"
description = "Buildbot for scummvms director tests"
authors = [{ name = "Roland van Laar", email = "roland@micite.net" }]
requires-python = ">=3.10,<4"
dependencies = [
  "environs",
  "treq",
  "buildbot[bundle]==3.9.2",
  "psycopg2>=2.9.5,<3.0.0",
  "certifi",
]

[dependency-groups]
dev = [
  "isort",
  "mypy",
  "pylint",
  "black",
  "ipdb",
]

[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
