<!doctype html>
<html>
    <head>
        <title>ScummVM</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="/cloud-style.css"/>
    </head>
    <body>
        <div class="container">
            <div class='header'>
                <img src="https://scummvm.org/images/scummvm_logo.png"/>
            </div>
            <div class="content">
                <p>Which cloud do you want to connect?</p>
                <div class="links-list">
                    <a href="/dropbox" class="link">
                        <img src="/images/dropbox.png" />
                        <b>Dropbox</b>
                    </a>
                    <a href="/onedrive" class="link">
                        <img src="/images/onedrive.png" />
                        <b>OneDrive</b>
                    </a>
                    <a href="/gdrive" class="link">
                        <img src="/images/google_drive.png" />
                        <b>Google Drive</b>
                    </a>
                    <a href="/box" class="link">
                        <img src="/images/box.png" />
                        <b>Box</b>
                    </a>
                </div>
            </div>
        </div>
    </body>
</html>
