<!doctype html>
<html>
    <head>
        <title>ScummVM</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="/cloud-style.css"/>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <img src="https://scummvm.org/images/scummvm_logo.png"/>
            </div>
            <div class="content">
                <p>Please enter the following code in ScummVM: <span class="shortcode"><?= $shortcode ?></span></p>
            </div>
        </div>
    </body>
</html>
